### ISSUE TITLE
不能改变 bedgeNo数量

### ISSUE THREAD

**Issue by webphplove** [LiuC520/flutter_bottom_tab_bar#2]
https://github.com/LiuC520/flutter_bottom_tab_bar/blob/master/lib/bottom_tab_bar_main.dart#L385
```
  Widget _buildBadge() {
    if (item.badge == null && (item.badgeNo == null || item.badgeNo.isEmpty)) {
      return Container();
    }
    if (item.badge != null) {
      return item.badge;
    }
    return Container(
      width: 24,
      padding: EdgeInsets.fromLTRB(0, 2, 0, 2),
      alignment: Alignment.center,
      decoration: BoxDecoration(
          color: badgeColor,
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.all(Radius.circular(10))),
      child: Text(
        '99+',
        style: TextStyle(fontSize: 10, color: Colors.white),
      ),
    );
  }
```
看来源码，99+是固定的

**Comment by lpy19930103** [comment]
> https://github.com/LiuC520/flutter_bottom_tab_bar/blob/master/lib/bottom_tab_bar_main.dart#L385
> 
> ```
>   Widget _buildBadge() {
>     if (item.badge == null && (item.badgeNo == null || item.badgeNo.isEmpty)) {
>       return Container();
>     }
>     if (item.badge != null) {
>       return item.badge;
>     }
>     return Container(
>       width: 24,
>       padding: EdgeInsets.fromLTRB(0, 2, 0, 2),
>       alignment: Alignment.center,
>       decoration: BoxDecoration(
>           color: badgeColor,
>           shape: BoxShape.rectangle,
>           borderRadius: BorderRadius.all(Radius.circular(10))),
>       child: Text(
>         '99+',
>         style: TextStyle(fontSize: 10, color: Colors.white),
>       ),
>     );
>   }
> ```
> 看来源码，99+是固定的

源码拿出来修改下就好了.
